# Generated by Django 5.1.6 on 2025-03-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='pnone',
            new_name='phone',
        ),
    ]
