# Generated by Django 5.1.6 on 2025-03-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe_app', '0003_alter_employee_dept_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='Dept',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='Last_name',
        ),
    ]
